server :
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: james
    password: jms990501
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  632328337364-q2riq342jkrsua7j3ud6iafmoqc3geie.apps.googleusercontent.com
            client-secret: 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
            scope:
             - email
             - profile
          facebook:
            client-id:  628218131880354
            client-secret: 95c3f71b98effa78b7f0682c75ff29d3
            scope:
             - email
             - public_profile
          naver:
            client-id: OGNfslkf7j0p0vOxfayj
            client-secret: hQe6IHai3i
            scope:
             - name
             - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #이 주소로 로그인 요청을 하면 네이버 로그인 창이 뜸
            token-uri: https://nid.naver.com//oauth2.0/token #토큰을 발급받는 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 정보를 받는 주소
            user-name-attribute: response #회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌


            #naver의 경우에는 공식 provider가 아니기 때문에 추가 정보를 알려줘야함
# ?? ??
#  mvc:
#    view:
#      prefix: /template/
#      suffix: .mustache
